language: node_js

node_js:
  - 0.10

env:
  global:
    - BROWSER_PROVIDER_READY_FILE=/tmp/sauce-connect-ready
    - LOGS_DIR=/tmp/angular2One-seed-build/logs
    - SAUCE_USERNAME=mlb6
    - SAUCE_ACCESS_KEY=61000c088427-ff5b-8b04-3219-277afc63

before_install:
  - npm install -g npm@latest

install:
  - mkdir -p $LOGS_DIR
  - ./scripts/sauce_connect_setup.sh
  - npm install
  - npm install -g bower
  - npm install -g gulp
  - npm install -g karma-cli
  - bower install
  - ./scripts/wait_for_browser_provider.sh

script:
  - ./scripts/test_on_sauce.sh
